import type { Course } from "./types";

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: "Solana Fundamentals",
    slug: "solana-fundamentals",
    description:
      "Master the core concepts of Solana — accounts, transactions, programs, and the runtime model. Build a solid foundation for everything that follows.",
    difficulty: "beginner",
    duration: 8,
    thumbnailUrl: null,
    track: "Solana Fundamentals",
    xpReward: 500,
    modules: [
      {
        id: 1,
        title: "Introduction to Solana",
        order: 1,
        lessons: [
          {
            id: 1,
            title: "What is Solana?",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 2,
            title: "The Account Model",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 3,
            title: "Transactions & Instructions",
            type: "content",
            content: "",
            order: 3,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 4,
            title: "Quiz: Solana Basics",
            type: "challenge",
            content: "",
            order: 4,
            xpReward: 50,
            challenge: null,
          },
        ],
      },
      {
        id: 2,
        title: "Programs & PDAs",
        order: 2,
        lessons: [
          {
            id: 5,
            title: "Program Derived Addresses",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 6,
            title: "Cross-Program Invocations",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 7,
            title: "Build a Counter Program",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 75,
            challenge: null,
          },
        ],
      },
      {
        id: 3,
        title: "Tokens on Solana",
        order: 3,
        lessons: [
          {
            id: 8,
            title: "SPL Token Standard",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 9,
            title: "Token-2022 Extensions",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 10,
            title: "Create Your Own Token",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 75,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: 2,
    title: "Anchor Framework Deep Dive",
    slug: "anchor-framework",
    description:
      "Learn the Anchor framework from scratch — macros, account validation, IDL generation, and testing. The fastest way to build Solana programs.",
    difficulty: "intermediate",
    duration: 12,
    thumbnailUrl: null,
    track: "Solana Fundamentals",
    xpReward: 800,
    modules: [
      {
        id: 4,
        title: "Anchor Basics",
        order: 1,
        lessons: [
          {
            id: 11,
            title: "Setting Up Anchor",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 12,
            title: "Account Macros",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 13,
            title: "Instruction Handlers",
            type: "content",
            content: "",
            order: 3,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 14,
            title: "Build a TODO dApp",
            type: "challenge",
            content: "",
            order: 4,
            xpReward: 100,
            challenge: null,
          },
        ],
      },
      {
        id: 5,
        title: "Advanced Anchor",
        order: 2,
        lessons: [
          {
            id: 15,
            title: "Custom Errors & Events",
            type: "content",
            content: "",
            order: 1,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 16,
            title: "CPIs in Anchor",
            type: "content",
            content: "",
            order: 2,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 17,
            title: "Testing with Bankrun",
            type: "content",
            content: "",
            order: 3,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 18,
            title: "Build a Voting Program",
            type: "challenge",
            content: "",
            order: 4,
            xpReward: 100,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-01-20T00:00:00.000Z",
  },
  {
    id: 3,
    title: "DeFi on Solana",
    slug: "defi-on-solana",
    description:
      "Understand DeFi primitives on Solana — token swaps, AMMs, lending protocols, and yield strategies. Build a mini DEX from scratch.",
    difficulty: "advanced",
    duration: 16,
    thumbnailUrl: null,
    track: "DeFi Developer",
    xpReward: 1200,
    modules: [
      {
        id: 6,
        title: "DeFi Foundations",
        order: 1,
        lessons: [
          {
            id: 19,
            title: "DeFi Landscape on Solana",
            type: "content",
            content: "",
            order: 1,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 20,
            title: "Constant Product AMMs",
            type: "content",
            content: "",
            order: 2,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 21,
            title: "Oracles & Price Feeds",
            type: "content",
            content: "",
            order: 3,
            xpReward: 30,
            challenge: null,
          },
        ],
      },
      {
        id: 7,
        title: "Building a DEX",
        order: 2,
        lessons: [
          {
            id: 22,
            title: "Liquidity Pool Design",
            type: "content",
            content: "",
            order: 1,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 23,
            title: "Swap Instructions",
            type: "content",
            content: "",
            order: 2,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 24,
            title: "Build a Mini DEX",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 150,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-02-01T00:00:00.000Z",
  },
  {
    id: 4,
    title: "Full Stack Solana dApps",
    slug: "full-stack-solana",
    description:
      "End-to-end dApp development — from Anchor programs to React frontends with wallet integration, transaction handling, and real-time updates.",
    difficulty: "intermediate",
    duration: 14,
    thumbnailUrl: null,
    track: "Full Stack Solana",
    xpReward: 900,
    modules: [
      {
        id: 8,
        title: "Frontend Foundations",
        order: 1,
        lessons: [
          {
            id: 25,
            title: "Wallet Adapter Setup",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 26,
            title: "Reading On-Chain Data",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 27,
            title: "Sending Transactions",
            type: "content",
            content: "",
            order: 3,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 28,
            title: "Build a Token Dashboard",
            type: "challenge",
            content: "",
            order: 4,
            xpReward: 75,
            challenge: null,
          },
        ],
      },
      {
        id: 9,
        title: "Production dApp",
        order: 2,
        lessons: [
          {
            id: 29,
            title: "Error Handling & Retries",
            type: "content",
            content: "",
            order: 1,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 30,
            title: "RPC Best Practices",
            type: "content",
            content: "",
            order: 2,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 31,
            title: "Full Stack Project",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 150,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-02-05T00:00:00.000Z",
  },
  {
    id: 5,
    title: "Solana Security & Auditing",
    slug: "solana-security",
    description:
      "Learn to identify and prevent common vulnerabilities in Solana programs. Covers signer validation, PDA misuse, reentrancy, and audit methodology.",
    difficulty: "advanced",
    duration: 10,
    thumbnailUrl: null,
    track: "Solana Fundamentals",
    xpReward: 1000,
    modules: [
      {
        id: 10,
        title: "Common Vulnerabilities",
        order: 1,
        lessons: [
          {
            id: 32,
            title: "Missing Signer Checks",
            type: "content",
            content: "",
            order: 1,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 33,
            title: "PDA Confusion Attacks",
            type: "content",
            content: "",
            order: 2,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 34,
            title: "Arithmetic Overflows",
            type: "content",
            content: "",
            order: 3,
            xpReward: 40,
            challenge: null,
          },
          {
            id: 35,
            title: "Spot the Bug",
            type: "challenge",
            content: "",
            order: 4,
            xpReward: 100,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: 6,
    title: "NFTs & Compressed NFTs",
    slug: "nfts-compressed",
    description:
      "Create, mint, and manage NFTs on Solana using Metaplex and state compression. Learn how compressed NFTs reduce costs by 1000x.",
    difficulty: "intermediate",
    duration: 10,
    thumbnailUrl: null,
    track: "Full Stack Solana",
    xpReward: 750,
    modules: [
      {
        id: 11,
        title: "NFT Standards",
        order: 1,
        lessons: [
          {
            id: 36,
            title: "Metaplex Token Metadata",
            type: "content",
            content: "",
            order: 1,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 37,
            title: "Collections & Verification",
            type: "content",
            content: "",
            order: 2,
            xpReward: 25,
            challenge: null,
          },
          {
            id: 38,
            title: "Mint an NFT Collection",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 75,
            challenge: null,
          },
        ],
      },
      {
        id: 12,
        title: "Compression",
        order: 2,
        lessons: [
          {
            id: 39,
            title: "State Compression & Merkle Trees",
            type: "content",
            content: "",
            order: 1,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 40,
            title: "Compressed NFTs with Bubblegum",
            type: "content",
            content: "",
            order: 2,
            xpReward: 30,
            challenge: null,
          },
          {
            id: 41,
            title: "Build a cNFT Minter",
            type: "challenge",
            content: "",
            order: 3,
            xpReward: 100,
            challenge: null,
          },
        ],
      },
    ],
    publishedAt: "2026-02-12T00:00:00.000Z",
  },
];
